### ISSUE TITLE
Queries using variables always fail validation

### ISSUE THREAD

**Issue by toresbe** [graphql-python/gql#164]
Hello! Nice library. I experienced a problem while using 3.0.0a3 with variables [as documented](https://gql.readthedocs.io/en/latest/usage/variables.html).

I found that if you try to use variable_values, the query will fail validation because variable_values are not passed along to the validation step. Therefore AFAICT, variable_values is currently borken.

No biggie for me; I'll work around it with string formatting. But I thought you might want to know.

See enclosed traceback:
```Traceback (most recent call last):
  File "./graphql_fetch.py", line 60, in <module>
    print(gh.get_repos_of_team('Frikanalen', 'developers'))
  File "./graphql_fetch.py", line 44, in get_repos_of_team
    "teamname": team_name,
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 172, in execute
    self.execute_async(document, *args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 131, in execute_async
    return await session.execute(document, *args, **kwargs)
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 416, in execute
    result = await self._execute(document, *args, **kwargs)
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 401, in _execute
    await self.fetch_and_validate(document)
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 350, in fetch_and_validate
    self.client.validate(document)
  File "/Users/toresbe/.local/share/virtualenvs/rosahelikopter-zySKoeU4/lib/python3.7/site-packages/gql/client.py", line 121, in validate
    raise validation_errors[0]
graphql.error.graphql_error.GraphQLError: Variable '$orgname' is not defined by operation 'MyQuery'.
```

Please see enclosed an example causing this problem.

```#!/usr/bin/env python3
import textwrap
import sys
import os
from IPython import embed

from gql import gql, Client, AIOHTTPTransport

class GithubQuery:
    def __init__(self, auth_token):
        if auth_token:
            self.token = auth_token
        else:
            raise ValueError("Invalid auth token supplied!")

        self.transport = AIOHTTPTransport(
            url="https://api.github.com/graphql",
            headers={'Authorization': f'bearer {self.token}'}
        )

        self.client = Client(transport=self.transport, fetch_schema_from_transport=True)

    def get_repos_of_team(self, org_name, team_name):
        query = gql(textwrap.dedent('''\
        query MyQuery {
          organization(login: $orgname) {
            team(slug: $teamname) {
              repositories(first: 10) {
                nodes {
                  name
                  description
                }
              }
            }
          }
        }'''))

        results = self.client.execute(
            query,
            variable_values={
                "orgname": org_name,
                "teamname": team_name,
            }
        )

        return results

def get_token_from_env():
    try:
        authorization_token = os.environ['GITHUB_USER_TOKEN']
    except KeyError:
        print('Authorization token must be set in $GITHUB_USER_TOKEN', file=sys.stderr)
        sys.exit(1)
    return authorization_token

if __name__ == '__main__':
    gh = GithubQuery(get_token_from_env())
    print(gh.get_repos_of_team('Frikanalen', 'developers'))
```

**Comment by leszekhanusz** [comment]
You need to put the variable keys and type in the query, something like this:
       
         query MyQuery ($orgname: String!, $teamname: String!) {
          organization(login: $orgname) {
            team(slug: $teamname) {
              repositories(first: 10) {
                nodes {
                  name
                  description
                }
              }
            }
          }

**Comment by toresbe** [comment]
Oh my goodness, how embarassing. I misread the example! Sorry to have bothered you.

**Comment by leszekhanusz** [comment]
No problem 😄
