### ISSUE TITLE
AssertionError: Task exception was never retrieved when running tests

### ISSUE THREAD

**Issue by leszekhanusz** [graphql-python/gql#170]
Sometimes when running the tests, the following warning appears:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-488' coro=<WebsocketsTransport._receive_data_loop() done, defined at /mnt/tera/git-repos/leszekhanusz/gql/gql/transport/websockets.py:333> exception=AssertionError()>
Traceback (most recent call last):
  File "/mnt/tera/git-repos/leszekhanusz/gql/gql/transport/websockets.py", line 340, in _receive_data_loop
    answer = await self._receive()
  File "/mnt/tera/git-repos/leszekhanusz/gql/gql/transport/websockets.py", line 169, in _receive
    assert self.websocket is not None
AssertionError
```

Even though the tests are passing.
It is probably harmless but we should investigate why it happens.

**Comment by leszekhanusz** [comment]
Should be fixed by #228
