### ISSUE TITLE
Updating GitHub Repository Branch Protection Rules - Part 2

### ISSUE THREAD

**Issue by kmbhanushali** [graphql-python/gql#176]
Hello!

I have been trying to integrate GitHub repo settings via Python and everything was going smoothly using the GitHub package. Unfortunately, the package does not contain any functions on creating new repo branch protection rules, so I had to switch to the gql package. I'm having a difficult time understanding the lingo surrounding this package so I was hoping to get some help here.

I had previously created another issue (issue #162) surrounding the subject. However after some more independent research I'm still stuck on the same issue.

My code:

```
from gql import gql, Client, AIOHTTPTransport
from gql.transport.requests import RequestsHTTPTransport
import asyncio
import traceback 

async def main():

    transport = AIOHTTPTransport(url="myURL",
                                  headers={'Authorization': 'bearer myToken'})

    # Using `async with` on the client will start a connection on the transport
    # and provide a `session` variable to execute queries on this connection
    async with Client(
        transport=transport,
        fetch_schema_from_transport=True,
        ) as session:

        # Execute single query
        query = gql("""
                mutation($input: CreateBranchProtectionRuleInput!) {
                    createBranchProtectionRule(input: $input) {
                        branchProtectionRule {
                          id
                        } 
                    }
                }
            """
            )

        input = {"repositoryId": "123456", "pattern": "release/*"}
        result = await session.execute(query, variable_values = input)
        print(result)

loop = asyncio.get_running_loop()
loop.create_task(main())
```

The code above does not return a GraphQL result and I'm not sure as to why. I can confirm that the URL I am trying to reach is a standard GitHub API. The following error is produced:

```
runfile('C:/Users/kmbhanushali/Documents/AEO_Controls/Tasks/03_Github_Repo_labels/branchProtectionRuleSetting.py', wdir='C:/Users/kmbhanushali/Documents/AEO_Controls/Tasks/03_Github_Repo_labels')
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<main() done, defined at C:\Users\kmbhanushali\Documents\AEO_Controls\Tasks\03_Github_Repo_labels\branchProtectionRuleSetting.py:6> exception=TransportProtocolError('Server did not return a GraphQL result')>
Traceback (most recent call last):
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\transport\aiohttp.py", line 127, in execute
    result = await resp.json()
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://github.build.ge.com/login?return_to=https://github.build.ge.com/aeocontrolstesting')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kmbhanushali\Documents\AEO_Controls\Tasks\03_Github_Repo_labels\branchProtectionRuleSetting.py", line 31, in main
    result = await session.execute(query, variable_values = input)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 338, in execute
    result = await self._execute(document, *args, **kwargs)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 327, in _execute
    await self.fetch_and_validate(document)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 278, in fetch_and_validate
    await self.fetch_schema()
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 351, in fetch_schema
    execution_result = await self.transport.execute(
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\transport\aiohttp.py", line 139, in execute
    raise TransportProtocolError("Server did not return a GraphQL result")
gql.transport.exceptions.TransportProtocolError: Server did not return a GraphQL result
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<main() done, defined at C:\Users\kmbhanushali\Documents\AEO_Controls\Tasks\03_Github_Repo_labels\branchProtectionRuleSetting.py:6> exception=TransportProtocolError('Server did not return a GraphQL result')>
Traceback (most recent call last):
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\transport\aiohttp.py", line 127, in execute
    result = await resp.json()
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\aiohttp\client_reqrep.py", line 1026, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://github.build.ge.com/login?return_to=https://github.build.ge.com/aeocontrolstesting')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kmbhanushali\Documents\AEO_Controls\Tasks\03_Github_Repo_labels\branchProtectionRuleSetting.py", line 31, in main
    result = await session.execute(query, variable_values = input)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 338, in execute
    result = await self._execute(document, *args, **kwargs)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 327, in _execute
    await self.fetch_and_validate(document)
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 278, in fetch_and_validate
    await self.fetch_schema()
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\client.py", line 351, in fetch_schema
    execution_result = await self.transport.execute(
  File "C:\Users\kmbhanushali\Anaconda3\lib\site-packages\gql\transport\aiohttp.py", line 139, in execute
    raise TransportProtocolError("Server did not return a GraphQL result")
gql.transport.exceptions.TransportProtocolError: Server did not return a GraphQL result
```

Any help would be appreciated :)

**Comment by leszekhanusz** [comment]
There is two types of GitHub API:
- the REST API
- GraphQL API.

Please read the [GitHub API docs](https://docs.github.com/en)

GQL will only help you with the GraphQL API :smiley: 

Please check that your URL ends with /graphql [as described in the docs](https://docs.github.com/en/free-pro-team@latest/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint)


If that does not help you, then:
 - update to the latest gql version
 - [activate debug logs](https://gql.readthedocs.io/en/latest/advanced/logging.html) so that you can send us better logs
