### ISSUE TITLE
NameError: name 'ip_address' is not defined

### ISSUE THREAD

**Issue by andreireiand** [graphql-python/gql#186]
Error when running on latest anaconda x64 win10:

Task exception was never retrieved
future: <Task finished name='Task-7' coro=<main() done, defined at Documents\python\graphql\graphql.py:7> exception=NameError("name 'ip_address' is not defined")>
Traceback (most recent call last):
  File "Documents\python\graphql\graphql.py", line 13, in main
    async with Client(
  File "Canaconda3\lib\site-packages\gql\client.py", line 250, in __aenter__
    await self.session.fetch_schema()
  File "anaconda3\lib\site-packages\gql\client.py", line 427, in fetch_schema
    execution_result = await self.transport.execute(
  File "anaconda3\lib\site-packages\gql\transport\aiohttp.py", line 198, in execute
    async with self.session.post(self.url, ssl=self.ssl, **post_args) as resp:
  File "anaconda3\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "anaconda3\lib\site-packages\aiohttp\client.py", line 404, in _request
    url = URL(str_or_url)
  File "anaconda3\lib\site-packages\yarl\_url.py", line 176, in __new__
    netloc = cls._make_netloc(
  File "Canaconda3\lib\site-packages\yarl\_url.py", line 765, in _make_netloc
    ret = cls._encode_host(host)
  File "anaconda3\lib\site-packages\yarl\_url.py", line 715, in _encode_host
    ip = ip_address(ip)
NameError: name 'ip_address' is not defined

for running code:

import asyncio

from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport

async def main():

    transport = AIOHTTPTransport(url="https://.........")

    # Using `async with` on the client will start a connection on the transport
    # and provide a `session` variable to execute queries on this connection
    async with Client(
        transport=transport, fetch_schema_from_transport=True,
    ) as session:

        # Execute single query
        query = gql(
            """
            query ...................
            """
        )

        result = await session.execute(query)
        print(result)

loop = asyncio.get_running_loop()
loop.create_task(main())

**Comment by leszekhanusz** [comment]
which version of yarl do you have ?

**Comment by leszekhanusz** [comment]
Please reopen if you have more information
