### ISSUE TITLE
[Question] How can I define a timeout to AIOHTTPTransport?

### ISSUE THREAD

**Issue by felinto-dev** [graphql-python/gql#203]
Hello!

I am facing this issue:
```py
Traceback (most recent call last):
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\twisted\internet\defer.py", line 662, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\scrapy\utils\defer.py", line 150, in f
    return deferred_from_coro(coro_f(*coro_args, **coro_kwargs))
  File "C:\Users\emers\Documents\spiders\gplzone\gplzone\pipeline\send_product_version_for_api.py", line 36, in process_item
    client.execute(
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\gql\client.py", line 167, in execute
    data: Dict[Any, Any] = loop.run_until_complete(
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\gql\client.py", line 127, in execute_async
    return await session.execute(document, *args, **kwargs)
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\gql\client.py", line 408, in execute
    result = await self._execute(document, *args, **kwargs)
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\site-packages\gql\client.py", line 396, in _execute
    return await asyncio.wait_for(
  File "c:\tools\anaconda3\envs\virtual_workspace\lib\asyncio\tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```

I am trying to upload a file to a GraphQL endpoint.
https://gql.readthedocs.io/en/v3.0.0a5/usage/file_upload.html

How can I define a timeout to AIOHTTPTransport?

**Comment by leszekhanusz** [comment]
You can specify the execute_timeout in the Client.

**execute_timeout** – The maximum time in seconds for the execution of a request before a TimeoutError is raised. Only used for async transports.

```python
client = Client(transport=sample_transport, execute_timeout=30)
```

**Comment by felinto-dev** [comment]
Helo!
I changed my client and I was able to confirm that it works. Thanks!
