### ISSUE TITLE
creating Client with GithubAPI fails

### ISSUE THREAD

**Issue by gliptak** [graphql-python/gql#251]
Code (authorization token is required):

```python
import os
from gql import Client
from gql.transport.requests import RequestsHTTPTransport

transport = RequestsHTTPTransport(
        url="https://api.github.com/graphql",
        headers={
            "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        },
    )

client = Client(transport=transport, fetch_schema_from_transport=True)
```

Versions:

```
gql                2.0.0
graphql-core       2.3.2
```

(Long) stacktrace:

```python
Traceback (most recent call last):
  File "/home/user/basic1.py", line 12, in <module>
    client = Client(transport=transport, fetch_schema_from_transport=True)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/gql/client.py", line 42, in __init__
    schema = build_client_schema(introspection)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 310, in build_client_schema
    return GraphQLSchema(
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/schema.py", line 106, in __init__
    self._type_map = GraphQLTypeMap(initial_types)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 31, in __init__
    self.update(reduce(self.reducer, types, OrderedDict()))  # type: ignore
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 100, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 104, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 104, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 100, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 104, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 100, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 104, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 104, in reducer
    reduced_map = cls.reducer(reduced_map, t)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 142, in reducer
    reduced_map = cls.reducer(reduced_map, getattr(field, "type", None))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 85, in reducer
    return cls.reducer(map_, type_.of_type)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/typemap.py", line 109, in reducer
    field_map = type_.fields
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/pyutils/cached_property.py", line 22, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/definition.py", line 198, in fields
    return define_field_map(self, self._fields)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/type/definition.py", line 212, in define_field_map
    field_map = field_map()
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 163, in <lambda>
    fields=lambda: build_field_def_map(object_introspection),
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 224, in build_field_def_map
    [
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 232, in <listcomp>
    args=build_input_value_def_map(f.get("args"), GraphQLArgument),
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 248, in build_input_value_def_map
    [
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 249, in <listcomp>
    (f["name"], build_input_value(f, argument_type))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 258, in build_input_value
    default_value=build_default_value(input_value_introspection),
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/utils/build_client_schema.py", line 244, in build_default_value
    return value_from_ast(parse_value(default_value), get_input_type(f["type"]))
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/language/parser.py", line 76, in parse_value
    return parse_value_literal(parser, False)
  File "/home/user/.local/share/virtualenvs/lDzRWh9v/lib/python3.9/site-packages/graphql/language/parser.py", line 512, in parse_value_literal
    raise unexpected(parser)
graphql.error.syntax_error.GraphQLSyntaxError: Syntax Error GraphQL (1:1) Unexpected Name "null"

1: null
   ^
```

Please let me know if other details are to be provided

**Comment by leszekhanusz** [comment]
gql version 2.x is not maintained anymore.
[Please install version 3.x](https://gql.readthedocs.io/en/v3.0.0b0/intro.html#installation)

**Comment by gliptak** [comment]
@leszekhanusz thank you for the pointer. should `v3.0.0b0`be tagged as latest in Pypi?

**Comment by leszekhanusz** [comment]
No, it is still a prerelease.
