### ISSUE TITLE
Big size content

### ISSUE THREAD

**Issue by Tradetechnique** [graphql-python/gql#357]
**Describe the bug**
My script : 

```
import asyncio

from gql import Client, gql
from gql.transport.aiohttp import AIOHTTPTransport


async def main():

    transport = AIOHTTPTransport(
        url="https://api.sorare.com/graphql",
        # headers = {"Authorization": "Bearer <TheUserAccessToken>"}
    )

    async with Client(transport=transport) as session:

        query = gql(
            """
            query {
                clubsReady{
                    id code slug pictureUrl pictureSecondaryUrl name subscriptionsCount optaId ready
                    lastFiveGames {
                        date awayGoals extraTimeScoreAway extraTimeScoreHome homeGoals id lowCoverage minute penaltyScoreAway penaltyScoreHome periodType scored status
                        awayTeam { ... on Club { id slug } }
                        competition { id slug }
                        homeTeam { ... on Club { id slug } }
                    }
                    upcomingGames(first:20) {
                        date awayGoals extraTimeScoreAway extraTimeScoreHome homeGoals id lowCoverage minute penaltyScoreAway penaltyScoreHome periodType scored status
                        awayTeam { ... on Club { id slug } }
                        competition { id slug }
                        homeTeam { ... on Club { id slug } }
                    }
                }
            } 
            """
        )

        result = await session.execute(query)
        print(result)

asyncio.run(main())
```

if you change "first:20" to "first:5" it's works. but here it's not works.
So I think it', works up to a certain size of the result. Beyond that, I get this error message:

```Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\gql\transport\aiohttp.py", line 296, in execute
    async with self.session.post(self.url, ssl=self.ssl, **post_args) as resp:
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\XXX\GitTrade\sorare-project\test.py", line 29, in <module>
    aa = asyncio.run(gql_query(query))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\XXX\GitTrade\sorare-project\utils.py", line 43, in gql_query
    result = await session.execute(gql(query), variable_values=variables, operation_name=operation_name)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\gql\client.py", line 1220, in execute
    result = await self._execute(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\site-packages\gql\client.py", line 1126, in _execute
    result = await asyncio.wait_for(
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DCEC0EBEE0>
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**To Reproduce**
Run my script with first:20 (not works) and first:5 (works)

**System info (please complete the following information):**
 - OS: Windows/Linux
 - Python version: 3
 - gql version: 3.4.0
 - graphql-core version: 3.2.0

**EDIT** : I changed the script for an easiest debug

**Comment by Tradetechnique** [comment]
Thanks for your answer.
And what about the error message : 
```no close frame received or sent``` ?

**Comment by leszekhanusz** [comment]
I don't know but a quick google point me to [this](https://websockets.readthedocs.io/en/stable/howto/faq.html#what-does-connectionclosederror-no-close-frame-received-or-sent-mean).

Please open another issue with logs if you still have problems.
