### ISSUE TITLE
No module named 'gql.transport.http'

### ISSUE THREAD

**Issue by antoine4ucsd** [graphql-python/gql#364]
Hello 
I am trying to us sierrapy for the script https://github.com/Wei-Shao/HIV-DRLink
I have installed the following
```
pip install --pre gql[all]
pip install --pre gql[aiohttp]
```
but when running by code

```
sierrapy fasta baseline_selected.fasta -g simple_mutations.gql  -o output.json
```
I get this error
```
Traceback (most recent call last):
  File "/mypath/bin/sierrapy", line 6, in <module>
    from sierrapy.cmds import main
  File "/mypath/lib/python3.10/site-packages/sierrapy/__init__.py", line 2, in <module>
    from .sierraclient import VERSION, SierraClient
  File "/mypath/lib/python3.10/site-packages/sierrapy/sierraclient.py", line 8, in <module>
    from gql.transport.http import HTTPTransport
ModuleNotFoundError: No module named 'gql.transport.http'
```

any suggestion?
thank you!
(working on a Mac)

**Comment by leszekhanusz** [comment]
It seems like this repo is using very old code with an updated gql requirements. It's a [bug in sierra-client](https://github.com/hivdb/sierra-client/issues/12), not an issue for this repo.
