### ISSUE TITLE
ImportError: cannot import name 'get_named_type' from 'graphql'

### ISSUE THREAD

**Issue by mdhvcd** [graphql-python/gql#369]
> Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/core/management/__init__.py", line 398, in execute
    autoreload.check_errors(django.setup)()
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/graphene_django/__init__.py", line 1, in <module>
    from .fields import DjangoConnectionField, DjangoListField
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/graphene_django/fields.py", line 5, in <module>
    from graphql_relay import (
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/graphql_relay/__init__.py", line 7, in <module>
    from .connection.connection import (
  File "/home/mdhv/graphql/env/lib/python3.10/site-packages/graphql_relay/connection/connection.py", line 3, in <module>
    from graphql import (
ImportError: cannot import name 'get_named_type' from 'graphql' (/home/mdhv/graphql/graphql/graphql/__init__.py)

Actually I am new to graphQl try to learn but while running the server I am getting above error, How to resolve this?
Blow are the installation

Django          4.1.3
graphene        3.1.1
graphene-django 3.0.0
graphql-core    3.2.3
graphql-relay   3.2.0
gql 3.4.0

**Comment by Cito** [comment]
Some of your packages are installed in a virtual env under `home/mdhv/graphql/env/` and some directly under `home/mdhv`, that's why you probably have an inconsistent installation with incompatible versions of the packages.

**Comment by mdhvcd** [comment]
But i have install all the packages when virtual env is active

**Comment by Cito** [comment]
Look at the last line in your traceback, you're trying to import something from `home/mdhv/graphql/graphql/graphql/` which is not in your env. Looks like you also called your own project "graphql" which makes it even more confusing and creates possible conflicts with the "graphql" core package.

**Comment by mdhvcd** [comment]
ok thanks

**Comment by mdhvcd** [comment]
Actually my project name is same as package name that's why getting this error after rename my project name works fine !
