### ISSUE TITLE
Unable to install gq

### ISSUE THREAD

**Issue by IrmantasMarozas** [graphql-python/gql#376]
**Describe the bug**
When trying to install `gq[aiohttp]` I am getting a `ModuleNotFoundError` error.
When trying to install specific version `gq[aiohttp]==3.4.0` I am getting a `Could not find a version that satisfies the requirement` error.

**To Reproduce**

1. Try to install:

```
pip install gq         
Collecting gq
  Using cached gq-0.0.3.tar.gz (4.8 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ls/vjdwg2gx30n5p15p4bkt8m080000gp/T/pip-install-gavdu3p2/gq_19f240d10bf9490c8c40dbec8fd5b89a/setup.py", line 4, in <module>
          from gq import __version__
        File "/private/var/folders/ls/vjdwg2gx30n5p15p4bkt8m080000gp/T/pip-install-gavdu3p2/gq_19f240d10bf9490c8c40dbec8fd5b89a/gq/__init__.py", line 1, in <module>
          from core import gq, mtable_to_dict, setup_maf
      ModuleNotFoundError: No module named 'core'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: There was an error checking the latest version of pip.
```

```
pip install gq==3.4.0         
ERROR: Could not find a version that satisfies the requirement gq==3.4.0 (from versions: 0.0.1.linux-x86_64, 0.0.2.linux-x86_64, 0.0.3.linux-x86_64, 0.0.1, 0.0.2, 0.0.3)
ERROR: No matching distribution found for gq==3.4.0
WARNING: There was an error checking the latest version of pip.
```

**Expected behavior**
Package should install.

**System info (please complete the following information):**
 - OS: macOS
 - Python version: 3.9
 - gql version: 3.4.0
 - graphql-core version: 3.2.1

**Comment by leszekhanusz** [comment]
It's `gql`, no `gq` :laughing:
