### ISSUE TITLE
When description is excluded from gql api unable to create Client

### ISSUE THREAD

**Issue by dangoodman5425** [graphql-python/gql#41]
```
transport = RequestsHTTPTransport(gql_endpoint, use_json=True)
client = Client(retries=0, transport=transport, fetch_schema_from_transport=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/gql/client.py", line 26, in __init__
    schema = build_client_schema(introspection)
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 306, in build_client_schema
    if schema_introspection["directives"]
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 305, in <listcomp>
    [build_directive(d) for d in schema_introspection["directives"]]
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 280, in build_directive
    directive_introspection.get("args", {}), GraphQLArgument
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 250, in build_input_value_def_map
    for f in input_value_introspection
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 250, in <listcomp>
    for f in input_value_introspection
  File "/home/dgoodman/anaconda3/lib/python3.6/site-packages/graphql/utils/build_client_schema.py", line 256, in build_input_value
    description=input_value_introspection["description"],
KeyError: 'description'
```

The GraphQL API I am hitting excludes description all together. Is this an issue worth addressing? If so I can open a PR to attempt to fix.

**Comment by Cito** [comment]
Fixed this in  graphql-python/graphql-core@0668626a0d8cd314440da9b59f1f6270f52e1d31.
