### ISSUE TITLE
Cannot connect to host countries.trevorblades.com:443 ssl:False

### ISSUE THREAD

**Issue by kunoka** [graphql-python/gql#481]
I ran into below error, can anyone help look into this, thanks.

Traceback (most recent call last):
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "C:\Program Files\Python\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Program Files\Python\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
ConnectionResetError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\git\python\Fitness Tracker Tool\main.py", line 39, in <module>
    execute()
  File "C:\git\python\Fitness Tracker Tool\main.py", line 34, in execute
    result = client.execute(query)
  File "C:\Program Files\Python\lib\site-packages\gql\client.py", line 469, in execute
    data = loop.run_until_complete(
  File "C:\Program Files\Python\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Program Files\Python\lib\site-packages\gql\client.py", line 366, in execute_async
    async with self as session:
  File "C:\Program Files\Python\lib\site-packages\gql\client.py", line 814, in __aenter__
    return await self.connect_async()
  File "C:\Program Files\Python\lib\site-packages\gql\client.py", line 795, in connect_async
    await self.session.fetch_schema()
  File "C:\Program Files\Python\lib\site-packages\gql\client.py", line 1661, in fetch_schema
    execution_result = await self.transport.execute(parse(introspection_query))
  File "C:\Program Files\Python\lib\site-packages\gql\transport\aiohttp.py", line 308, in execute
    async with self.session.post(self.url, ssl=self.ssl, **post_args) as resp:
  File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files\Python\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Program Files\Python\lib\site-packages\aiohttp\connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host countries.trevorblades.com:443 ssl:False [None]v

**Comment by leszekhanusz** [comment]
Which code did you use?
It seems like a network connectivity issue. Are you behind a corporate firewall or something interfering with your network?
